version: '3.8'

services:
  DB:
    image: mysql:8.0
    container_name: DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: workdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  aplicacao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aplicacao
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=DB
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=workdb
      - DB_PORT=3306
    volumes:
      - .:/app
    command: npm start
    depends_on:
      - DB
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
